### PR TITLE
Student email history

### PR DESCRIPTION
**Pull request by BertGuillemyn**
~Currently only uses placeholder data~

### CODE REVIEW

**Review by stijndcl — CHANGES_REQUESTED** [review]
General email page:
- Whenever I click the Search button it sends **4** requests
- One of those requests has `?page=X` where X increases every time I send the request, even though there are no results

**Comment by BertGuillemyn** [comment]
> General email page:
> 
>     * Whenever I click the Search button it sends **4** requests
> 
>     * One of those requests has `?page=X` where X increases every time I send the request, even though there are no results

I looked into this, and what happened was that, when filtering, the page numbers didn't reset to 0, but kept increasing. It turns out it's quite hard to reset this page number (https://github.com/danbovey/react-infinite-scroller/issues/12). I fixed this by changing the component's key to remount it, but this is quite ugly. I also changed some other things because there were too many unnecessary requests sent. 
I think the current version works, but maybe someone else should take a look at this and possibly implement a better way.

**Review by stijndcl — CHANGES_REQUESTED** [review]
You can send emails via the /emails screen, but only to students who have already received an email. How do you send the initial/first email?

Also - the table on `/students/:id/emails` should be hidden when there are no results, and display a message instead.

**Comment by BertGuillemyn** [comment]
> You can send emails via the /emails screen, but only to students who have already received an email. How do you send the initial/first email?
> 
> Also - the table on `/students/:id/emails` should be hidden when there are no results, and display a message instead.
The first issue has been solved as discussed in the previous meeting. When a student is first created, an "applied" state will need to be created.
The second issue has also been solved.
All merge conflicts are also fixed.

**Review by stijndcl — APPROVED** [review]

**Pull request merged**
