### PR TITLE
Create edition page updates

### LINKED ISSUE #353: [FEAT] "Back" button on Create Edition page

### PR DESCRIPTION
**Pull request by Tiebe-Vercoutter**
Added a cancel button, closes #353 
Changed the create button to the one @stijndcl made
Restyled Form input fields
Added toasts for different error messages (only after an api call is sent)
afbeelding

### CODE REVIEW

**Comment by stijndcl** [comment]
I like those input fields! Maybe an idea to apply that styling to the Common component? That way we can use it everywhere!

**Comment by Tiebe-Vercoutter** [comment]
> I like those input fields! Maybe an idea to apply that styling to the Common component? That way we can use it everywhere!

Yes thats a good idea! Did it like this:
```
export const FormGroup = styled(Form.Group)`
    margin-top: 20px;
    .form-control {
        background-color: #131329;
        color: white;
        border: none; // can also be background-color
    }
`;
```

**Review by stijndcl — CHANGES_REQUESTED** [review]
- I've noticed that you still show the error messages on-screen as well. Now that we have the toasts, can't those go? Otherwise people will see the same messages twice.
- Invalid forms are more of an error than a warning, so I feel like `toast.error` fits better for those.
- Now that I've turned your input fields into common components, consider replacing them in here :)

**Comment by Tiebe-Vercoutter** [comment]
> * I've noticed that you still show the error messages on-screen as well. Now that we have the toasts, can't those go? Otherwise people will see the same messages twice.

Don't really know, Sometimes it's nice to see to which field the error belongs to.  But I get what you're saying 🤔 

>     * Invalid forms are more of an error than a warning, so I feel like `toast.error` fits better for those.

yes

>     * Now that I've turned your input fields into common components, consider replacing them in here :)

yes

**Comment by stijndcl** [comment]
> Don't really know, Sometimes it's nice to see to which field the error belongs to. But I get what you're saying thinking
That's why you give the field an `invalid` state so it gets a nice big red outline & an exclamation mark :p should be clear what field is wrong, no?

**Comment by Tiebe-Vercoutter** [comment]
> > Don't really know, Sometimes it's nice to see to which field the error belongs to. But I get what you're saying thinking
> 
> That's why you give the field an `invalid` state so it gets a nice big red outline & an exclamation mark (which you did, quickly glancing at your code) :p should be clear what field is wrong, no?

So only invalid state but no message?

**Comment by stijndcl** [comment]
I'd personally do it like that, cause the message already appears in the toast.

**Review by stijndcl — APPROVED** [review]

**Pull request merged**
