### PR TITLE
questions and answers of student

### PR DESCRIPTION
**Pull request by ClementDeloof**

### CODE REVIEW

**Review by FKD13 — COMMENTED** [review]
Looks good!

How hard would it be to also render the following as an url?
png

**Review by FKD13 — APPROVED** [review]
We have the required info to identify links in the backend, but it is not passed to the frontend. Probably not worth changing at this point

**Comment by ClementDeloof** [comment]
> Looks good!
> 
> How hard would it be to also render the following as an url? png

Since the components just loops over the questions and answers, all answers will be seen as normal strings. I would have to hardcode this question to be able to make a link out of it, but I think that would be pretty ugly.

**Review by stijndcl — APPROVED** [review]
Good work!

**Pull request merged**
