### PR TITLE
Students session storage

### PR DESCRIPTION
**Pull request by ClementDeloof**

### CODE REVIEW

**Review by Tiebe-Vercoutter — APPROVED** [review]
Everything is working as expected

**Review by stijndcl — CHANGES_REQUESTED** [review]
- Use an enum for the keys so we can't make any mistakes against them (typo's)
- Please move these functions over the `utils/session-storage` to make the components a bit cleaner. All the getters and setters can be over there, and you can include the `null` checks/default values as well.
- You don't need the `!`-operator if you return a default value (see previous point), for example checkboxes can be off by default, search fields are empty by default, ...

For an example of what we're looking for, check the existing code: https://github.com/SELab-2/OSOC-3/blob/develop/frontend/src/utils/session-storage/current-edition.ts

**Comment by ClementDeloof** [comment]
@stijndcl I completed all suggested changes and it indeed looks cleaner like this!
As is mentioned in #447, I fixed the reset filter button here, because the session storage also had to apply changes to this component.

**Comment by ClementDeloof** [comment]
@stijndcl @Tiebe-Vercoutter , I implemented all the requested changes and it is now more intuitive and satisfying

https://user-images.githubusercontent.com/68028701/169178169-f6b47147-5099-45f8-b3c3-4f86d9d4b44d.mp4

!

**Review by stijndcl — APPROVED** [review]

**Pull request merged**
