### PR TITLE
Websockets frontend

### PR DESCRIPTION
**Pull request by stijndcl**
Made websockets in the frontend.

I wish I had another week to make this a bit more abstract, as it's a bit ugly now, but it is what it is. We chose for flexible & efficient sockets over hard-refreshing the whole page (like _another group that I won't name_ does), which comes with a more complex implementation behind the scenes.

To test, you can simply open two windows next to each other (can be on the same account, doesn't matter) and make some changes to students & projects. Just make sure you're on the right edition, because #524 hasn't been merged yet as of now.

### CODE REVIEW

**Review by SeppeM8 — CHANGES_REQUESTED** [review]
Very satisfying!

Some small issues:
- Suggestions field (with motivations) doesn't change when a coach makes a suggestion
- When the confirmed filter is set (to yes) and another admin makes a final decision (yes), the new "yes"-student doesn't show up in the filtered studentslist

**Comment by stijndcl** [comment]
> Very satisfying!
> 
> Some small issues:
> 
> * Suggestions field (with motivations) doesn't change when a coach makes a suggestion
> * When the confirmed filter is set (to yes) and another admin makes a final decision (yes), the new "yes"-student doesn't show up in the filtered studentslist

I'll take a look!

**Comment by stijndcl** [comment]
> Very satisfying!
> 
> Some small issues:
> 
> * Suggestions field (with motivations) doesn't change when a coach makes a suggestion
> * When the confirmed filter is set (to yes) and another admin makes a final decision (yes), the new "yes"-student doesn't show up in the filtered studentslist

I have returned.

The first one should work, can't reproduce the issue. It's possible that it takes a second, or that you have to be focused on the tab. This is what I get:

https://user-images.githubusercontent.com/60451863/169592090-f18c35b1-31c9-466f-8bec-3ba325f7ef8d.mp4

The second one is a bit harder, because I'd have to match the student against all of the current filters. This also includes things like `only students you've suggested for`, which means I'd have to send an API call. Do we want to do this for every single websocket event?

**Comment by FKD13** [comment]
I think this would give conflict with the infinite scrolling? If not then it might be worth it

**Review by FKD13 — DISMISSED** [review]

**Review by SeppeM8 — DISMISSED** [review]
Works like a charm!

**Review by SeppeM8 — APPROVED** [review]

**Pull request merged**
